### ISSUE TITLE
wouldn't download

### ISSUE THREAD

**Issue by ynweinberger** [EpicUnknown/wco-dl#12]
Subject : downloading show
Traceback (most recent call last):
  File "__main__.py", line 11, in <module>
  File "__main__.py", line 65, in Main
  File "Lifter.py", line 43, in __init__
  File "Lifter.py", line 140, in download_show
IndexError: list index out of range
[15808] Failed to execute script __main__

Command Line Arguments You Gave : C:\Users\HP\Downloads>wco-dl-64.exe -i "https://www.wcostream.com/anime/shaun-the-sheep" -epr 8 -v

Verbose Log Link : https://pastebin.com/Yw9gsMKU

Long Explanation : i was trying to download this show it got to episode 7 then failed so i tried getting episode 8 on its own but it failed
[Error Log.log](https://github.com/EpicUnknown/wco-dl/files/4406236/Error.Log.log)

**Comment by ynweinberger** [comment]
similarly i got thiss issue on a different show:
[wco-dl] - Downloading Victor And Valentino-Season 1-Episode 18
Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 665, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 376, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
  File "site-packages\urllib3\connection.py", line 386, in connect
  File "site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 439, in send
  File "site-packages\urllib3\connectionpool.py", line 719, in urlopen
  File "site-packages\urllib3\util\retry.py", line 400, in increment
  File "site-packages\urllib3\packages\six.py", line 734, in reraise
  File "site-packages\urllib3\connectionpool.py", line 665, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 376, in _make_request
  File "site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
  File "site-packages\urllib3\connection.py", line 386, in connect
  File "site-packages\urllib3\util\ssl_.py", line 370, in ssl_wrap_socket
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 11, in <module>
  File "__main__.py", line 65, in Main
  File "Lifter.py", line 43, in __init__
  File "Lifter.py", line 158, in download_show
  File "Downloader.py", line 29, in __init__
  File "site-packages\requests\sessions.py", line 546, in get
  File "site-packages\cfscrape\__init__.py", line 120, in request
  File "site-packages\requests\sessions.py", line 533, in request
  File "site-packages\requests\sessions.py", line 646, in send
  File "site-packages\requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))
[12928] Failed to execute script __main__

**Comment by ynweinberger** [comment]
thanks for that ill see if i can replicate the other one
