### ISSUE TITLE
tried again

### ISSUE THREAD

**Issue by ynweinberger** [EpicUnknown/wco-dl#13]
i got here by tring to download the whole series. got to 39 and then stopped so i tried 40 individually
my command was: 
C:\Users\HP\Downloads>wco-dl-64.exe -i "https://www.wcostream.com/anime/shaun-the-sheep" -epr 40-40 -v
this was the result: 
downloading show
Traceback (most recent call last):
  File "__main__.py", line 11, in <module>
  File "__main__.py", line 65, in Main
  File "Lifter.py", line 43, in __init__
  File "Lifter.py", line 141, in download_show
  File "Lifter.py", line 141, in <listcomp>
TypeError: 'NoneType' object is not subscriptable
[20500] Failed to execute script __main__

and here is the error log generated: https://pastebin.com/XpwjuUu7

here is the details from trying to download the series **https://pastebin.com/ddJeJCcc**

**Comment by EpicUnknown** [comment]
I believe this was fixed with pull #14 
I can make a new executable if needed if you do not know how. Please let me know
