### ISSUE TITLE
Error during download

### ISSUE THREAD

**Issue by samuelrhaynes** [EpicUnknown/wco-dl#16]
Hi, thanks for writing this script

I'm trying to download spongebob for the kids, I've installed the most recent version of your script. It downloads the most recent episode then shows this error?

Traceback (most recent call last):
  File "__main__.py", line 12, in <module>
  File "__main__.py", line 73, in Main
  File "Lifter.py", line 52, in __init__
  File "Lifter.py", line 178, in download_show
IndexError: list index out of range
[26064] Failed to execute script __main__

Thank you!

**Comment by EpicUnknown** [comment]
So that error means that it was unable to find an HD version of the video and I don't have a catch statement that handles that failure. It very rarely happened during my testing so I haven't fixed it because it's on specific videos.
