### ISSUE TITLE
Unable to download - backup url

### ISSUE THREAD

**Issue by pmcfarland** [EpicUnknown/wco-dl#24]
I'm trying to download a video and I'm encountering an error that is preventing it from downloading. It reports that it's missing a positional argument backup url.

```
Downloading single
Traceback (most recent call last):
  File "__main__.py", line 12, in <module>
  File "__main__.py", line 89, in Main
  File "Lifter.py", line 60, in __init__
  File "Lifter.py", line 136, in download_single
TypeError: __init__() missing 1 required positional argument: 'backup_url'
[6584] Failed to execute script __main__
```

**Comment by Real-Ryououki** [comment]
I am also having the same issue.  With almost exactly the same output error:

Downloading single
Traceback (most recent call last):
  File "__main__.py", line 12, in <module>
  File "__main__.py", line 89, in Main
  File "Lifter.py", line 60, in __init__
  File "Lifter.py", line 136, in download_single
TypeError: __init__() missing 1 required positional argument: 'backup_url'
[16612] Failed to execute script __main__
